ALTER TABLE `employee_performance` MODIFY COLUMN `averageRating` decimal(3,2);--> statement-breakpoint
ALTER TABLE `favorites` ADD CONSTRAINT `idx_favorites_user_product` UNIQUE(`userId`,`productId`);--> statement-breakpoint
CREATE INDEX `idx_bunkers_machine` ON `bunkers` (`machineId`);--> statement-breakpoint
CREATE INDEX `idx_bunkers_ingredient` ON `bunkers` (`ingredientId`);--> statement-breakpoint
CREATE INDEX `idx_cart_user` ON `cart_items` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_cart_user_product` ON `cart_items` (`userId`,`productId`);--> statement-breakpoint
CREATE INDEX `idx_favorites_user` ON `favorites` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_assignments_machine` ON `machine_assignments` (`machineId`);--> statement-breakpoint
CREATE INDEX `idx_assignments_employee` ON `machine_assignments` (`employeeId`);--> statement-breakpoint
CREATE INDEX `idx_assignments_status` ON `machine_assignments` (`assignmentStatus`);--> statement-breakpoint
CREATE INDEX `idx_assignments_employee_status` ON `machine_assignments` (`employeeId`,`assignmentStatus`);--> statement-breakpoint
CREATE INDEX `idx_assignments_machine_status` ON `machine_assignments` (`machineId`,`assignmentStatus`);--> statement-breakpoint
CREATE INDEX `idx_maintenance_machine` ON `maintenance_history` (`machineId`);--> statement-breakpoint
CREATE INDEX `idx_maintenance_employee` ON `maintenance_history` (`employeeId`);--> statement-breakpoint
CREATE INDEX `idx_maintenance_status` ON `maintenance_history` (`maintenanceStatus`);--> statement-breakpoint
CREATE INDEX `idx_maintenance_scheduled` ON `maintenance_history` (`scheduledDate`);--> statement-breakpoint
CREATE INDEX `idx_mixers_machine` ON `mixers` (`machineId`);--> statement-breakpoint
CREATE INDEX `idx_mixers_status` ON `mixers` (`mixerStatus`);--> statement-breakpoint
CREATE INDEX `idx_notifications_user` ON `notifications` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_notifications_user_read` ON `notifications` (`userId`,`isRead`);--> statement-breakpoint
CREATE INDEX `idx_notifications_created` ON `notifications` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_orders_user` ON `orders` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_orders_status` ON `orders` (`status`);--> statement-breakpoint
CREATE INDEX `idx_orders_created` ON `orders` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_orders_user_status` ON `orders` (`userId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_orders_machine` ON `orders` (`machineId`);--> statement-breakpoint
CREATE INDEX `idx_points_user` ON `points_transactions` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_points_user_created` ON `points_transactions` (`userId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_points_created` ON `points_transactions` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_sales_created` ON `sales_records` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_sales_machine` ON `sales_records` (`machineCode`);--> statement-breakpoint
CREATE INDEX `idx_sales_order_resource` ON `sales_records` (`orderResource`);--> statement-breakpoint
CREATE INDEX `idx_sales_batch` ON `sales_records` (`importBatchId`);--> statement-breakpoint
CREATE INDEX `idx_sales_created_resource` ON `sales_records` (`createdAt`,`orderResource`);--> statement-breakpoint
CREATE INDEX `idx_tasks_assigned` ON `tasks` (`assignedTo`);--> statement-breakpoint
CREATE INDEX `idx_tasks_status` ON `tasks` (`taskStatus`);--> statement-breakpoint
CREATE INDEX `idx_tasks_machine` ON `tasks` (`machineId`);--> statement-breakpoint
CREATE INDEX `idx_tasks_due` ON `tasks` (`dueDate`);--> statement-breakpoint
CREATE INDEX `idx_tasks_assigned_status` ON `tasks` (`assignedTo`,`taskStatus`);--> statement-breakpoint
CREATE INDEX `idx_tasks_priority_status` ON `tasks` (`priority`,`taskStatus`);--> statement-breakpoint
CREATE INDEX `idx_quest_progress_user` ON `user_daily_quest_progress` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_quest_progress_user_date` ON `user_daily_quest_progress` (`userId`,`questDate`);--> statement-breakpoint
CREATE INDEX `idx_quest_progress_user_quest_date` ON `user_daily_quest_progress` (`userId`,`questId`,`questDate`);--> statement-breakpoint
CREATE INDEX `idx_worklogs_employee` ON `work_logs` (`employeeId`);--> statement-breakpoint
CREATE INDEX `idx_worklogs_machine` ON `work_logs` (`machineId`);--> statement-breakpoint
CREATE INDEX `idx_worklogs_status` ON `work_logs` (`workStatus`);--> statement-breakpoint
CREATE INDEX `idx_worklogs_start` ON `work_logs` (`startTime`);--> statement-breakpoint
CREATE INDEX `idx_worklogs_employee_status` ON `work_logs` (`employeeId`,`workStatus`);--> statement-breakpoint
ALTER TABLE `employee_performance` DROP COLUMN `createdAt`;--> statement-breakpoint
ALTER TABLE `employee_performance` DROP COLUMN `updatedAt`;